### ISSUE TITLE
specify all the dependencies version in setup.py

### ISSUE THREAD

**Issue by yamyamyuo** [apache/incubator-superset#5527]
Make sure these boxes are checked before submitting your issue - thank you!

- [ x ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ x ] I have reproduced the issue with at least the latest released version of superset
- [ x ] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.26.2
problem with pandas version: 0.20.3

### Expected results
run charts, the charts should render some beautiful graphs. 

### Actual results
raise error 'Series' object has no attribute 'items'

### Steps to reproduce
when setup everything, click one example charts, the charts cannot rendered.
This is because Pandas version is too low. after upgrading pandas to 0.23.3, this error disappear.

<img width="537" alt="screen shot 2018-07-31 at 8 16 41 pm" src="https://user-images.githubusercontent.com/8351385/43459301-b1f773a0-94ff-11e8-9737-cecc69a42981.png">

Please specify all the dependencies installation version.
The version of pandas is not enough, at least 0.23.3 will solve this problem.
https://github.com/apache/incubator-superset/blob/c1e6c68a3ed31d3875b6d9dfac1484d8897d6561/setup.py#L79

**Comment by yamyamyuo** [comment]
@mistercrunch @williaster specify all the third party lib version is a very good engineering practice.
I have came across another similar problem. `markdown` has new version available, when I build superset image half years later, it somehow installed the newest version which failed my older features. 
In superset == 0.26.2, markdown should be `2.6.11` otherwise if you run `superset version`, it fails.

Strongly advice to specify all the version in `setup.py`, otherwise, don't know what will come across in the long run.

**Comment by mistercrunch** [comment]
@john-bodley bringing this up again as many people are having issues with a `pip install superset` at the moment. I wonder if we should go to a default of pinning most library and allowing version ranges for libs where people may need flexibility (pandas, celery. //)

**Comment by john-bodley** [comment]
@mistercrunch thanks for raising this. I've been re-looking into how to best configure Python applications (as opposed to packages). It seems that the recommended approach is not to pin specific versions in `setup.py` but rather in `requirements.txt` (or similar) per [here](https://caremad.io/posts/2013/07/setup-vs-requirement/) and others.

It seems in our case your `setup.py` is not prescriptive enough or contains lower bounds which aren't viable, i.e., clearly `pandas==0.18.0` is not suffice for `superset==0.26.2` and the `setup.py` should be modified to include viable versions. I believe this is the responsibility of the developer who is creating a breaking dependency change to update `setup.py` and re-generate `requirements.txt`.

**Comment by mistercrunch** [comment]
@john-bodley  the big question is whether we think `pip install superset` should just work or be allowed to get in a bad state (open version guarantees it will). Without upper-bounds on version ranges, we're kind of asking for it. For instance we know that celery>=5.0.0, when it comes out, is very very likely to break things in Superset.

We need to either: 
* add an extra steps in the installation docs recommending cloning the repo and installing the requirements.txt file
* actively managing ranges in setup.py, quickly release with bound ranges as soon as something is known to be broken
* ping setup.py and tell users that if they want to mess with lib versions, they can make their own build by messing with `setup.py` in their fork, this also means manually, periodically bumping to make sure we don't use stale libs 
* add a step in the build matrix that checks whether an indeterministic `pip install superset` (without reqs.txt) currently leads to a broken build, that way we know quickly when `pip install superset` is broken
* ?

**Comment by john-bodley** [comment]
@mistercrunch, I believe that `pip install superset` should work, however installing Superset is not suffice due to environment specific dependencies. It may be good to understand how other organizations deploy it. Could there be a circumstance where people need to use a different SQLAlchemy version based on their database?

I agree with your points, especially 1, 2, and 4. Let me keep looking into this.

**Comment by mistercrunch** [comment]
I can tackle 1

**Comment by milimetric** [comment]
@john-bodley maybe this helps, you can and should only specify requirements in one place.  If you like requirements.txt, you can pull them into setup.py with a trick like this:

https://github.com/wikimedia/analytics-wikimetrics/blob/master/setup.py#L25

And for everyone's sanity, it's always good to pin exact or at least compatible versions (^X.Y.Z should work if everyone takes semver seriously).  You can even make a build process through setup.py that installs all the node dependencies too.

**Comment by elukey** [comment]
@mistercrunch when you say "version ranges" for setup.py, do you mean that from the new upstream version (ideally 0.29?) all the deps in setup.py will not cause a broken build with bdist_wheel (0.26.3 cannot be built in this way for example) ? If so it would be great to have a documentation about how to properly build superset, so everybody is on the same page. What do you think?
