### ISSUE TITLE
'NoneType' object has no attribute 'fillna' with daylight savings error in time-series visualizations. 

### ISSUE THREAD

**Issue by klaaskooistra** [apache/incubator-superset#4615]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.23.2

### Expected results
When showing visualization using a postgresql backend on time-series without a timezone, I should see the visualization. 

### Actual results
All visualizations show: 'NoneType' object has no attribute 'fillna'. This however only happens when I want to plot a time-series across daylight savings periods. 

### Steps to reproduce
Create Postgresql table with timestamps without timezone, but with DST. 
Try to create time-series visualization crossing the DST date as your date/time to plot against.

First time posting an issue, if anything else is needed, please let me know.

**Comment by klaaskooistra** [comment]
Did some more digging. Probably related to #4319  
AT TIME ZONE should only be used when date/time field has a timezone. 
Is this correct @habalux ?

**Comment by xrmx** [comment]
Python stacktrace from logs please.

**Comment by klaaskooistra** [comment]
Stacktrace:



> Traceback (most recent call last):
>   File "/Code/superset/venv/lib/python3.6/site-packages/pandas/core/tools/datetimes.py", line 303, in _convert_listlike
>     values, tz = tslib.datetime_to_datetime64(arg)
>   File "pandas/_libs/tslib.pyx", line 1870, in pandas._libs.tslib.datetime_to_datetime64
> ValueError: Array must be all same time zone
> 
> During handling of the above exception, another exception occurred:
> 
>
> Traceback (most recent call last):
>   File "/Code/superset/venv/lib/python3.6/site-packages/superset/viz.py", line 325, in get_df_payload
>     df = self.get_df(query_obj)
>   File "/Code/superset/venv/lib/python3.6/site-packages/superset/viz.py", line 162, in get_df
>     df[DTTM_ALIAS], utc=False, format=timestamp_format)
>   File "/Code/superset/venv/lib/python3.6/site-packages/pandas/core/tools/datetimes.py", line 373, in to_datetime
>     values = _convert_listlike(arg._values, True, format)
>   File "/Code/superset/venv/lib/python3.6/site-packages/pandas/core/tools/datetimes.py", line 306, in _convert_listlike
>     raise e
>   File "/Code/superset/venv/lib/python3.6/site-packages/pandas/core/tools/datetimes.py", line 294, in _convert_listlike
>     require_iso8601=require_iso8601
>   File "pandas/_libs/tslib.pyx", line 2156, in pandas._libs.tslib.array_to_datetime
>   File "pandas/_libs/tslib.pyx", line 2202, in pandas._libs.tslib.array_to_datetime
> ValueError: Tz-aware datetime.datetime cannot be converted to datetime64 unless utc=True
> 2018-03-14 14:43:07,097:ERROR:root:'NoneType' object has no attribute 'fillna'
> Traceback (most recent call last):
>   File "/Code/superset/venv/lib/python3.6/site-packages/superset/views/core.py", line 1059, in generate_json
>     payload = viz_obj.get_payload()
>   File "/Code/superset/venv/lib/python3.6/site-packages/superset/viz.py", line 293, in get_payload
>     payload['data'] = self.get_data(df)
>   File "/Code/superset/venv/lib/python3.6/site-packages/superset/viz.py", line 1139, in get_data
>     df = self.process_data(df)
>   File "/Code/superset/venv/lib/python3.6/site-packages/superset/viz.py", line 1044, in process_data
>     df = df.fillna(0)
> AttributeError: 'NoneType' object has no attribute 'fillna'

**Comment by mistercrunch** [comment]
I think this is addressed on `master`

**Comment by klaaskooistra** [comment]
Thanks, not sure if it is fixed in .25rc1, however after upgrading to 0.24 a new error arises. 

Tz-aware datetime.datetime cannot be converted to datetime64 unless utc=True

Stacktrace:

```
Traceback (most recent call last):
  File "/var/superset/local/lib/python2.7/site-packages/superset/viz.py", line 329, in get_df_payload
    df = self.get_df(query_obj)
  File "/var/superset/local/lib/python2.7/site-packages/superset/viz.py", line 161, in get_df
    df[DTTM_ALIAS], utc=False, format=timestamp_format)
  File "/var/superset/local/lib/python2.7/site-packages/pandas/core/tools/datetimes.py", line 373, in to_datetime
    values = _convert_listlike(arg._values, True, format)
  File "/var/superset/local/lib/python2.7/site-packages/pandas/core/tools/datetimes.py", line 306, in _convert_listlike
    raise e
ValueError: Tz-aware datetime.datetime cannot be converted to datetime64 unless utc=True
```

**Comment by klaaskooistra** [comment]
Validated on .25.0: Issue still persists. Same stacktrace as above.

**Comment by Madhuri2000** [comment]
facing this issue in 0.23.3 version

**Comment by mistercrunch** [comment]
@Madhuri2000 `0.23.3` is from 2018! Please upgrade you'll be amazed :)
