### ISSUE TITLE
RLS not working on 0.38.0

### ISSUE THREAD

**Issue by oscarostlundgs** [apache/incubator-superset#11878]
RLS Filters seem broken on 0.38.0. 

### Expected results

On 0.37.2, RLS filters work correctly and are applied to queries when conditions are met. The same behavior is expected for 0.38 with Regular filters. 

### Actual results

When querying the data through Superset, the result pane shows an error saying: `AttributeError: 'result' object has no attribute 'group_key'`. This issue is not resolved by adding a group_key to the filter. 

#### Screenshots

```
Traceback (most recent call last):
  File "/home/superset/venv/lib/python3.7/site-packages/superset/viz.py", line 532, in get_df_payload
    df = self.get_df(query_obj)
  File "/home/superset/venv/lib/python3.7/site-packages/superset/viz.py", line 287, in get_df
    self.results = self.datasource.query(query_obj)
  File "/home/superset/venv/lib/python3.7/site-packages/superset/connectors/sqla/models.py", line 1248, in query
    query_str_ext = self.get_query_str_extended(query_obj)
  File "/home/superset/venv/lib/python3.7/site-packages/superset/connectors/sqla/models.py", line 721, in get_query_str_extended
    sqlaq = self.get_sqla_query(**query_obj)
  File "/home/superset/venv/lib/python3.7/site-packages/superset/connectors/sqla/models.py", line 1054, in get_sqla_query
    where_clause_and += self._get_sqla_row_level_filters(template_processor)
  File "/home/superset/venv/lib/python3.7/site-packages/superset/connectors/sqla/models.py", line 818, in _get_sqla_row_level_filters
    filters_grouped[filter_.group_key or filter_.id].append(clause)
AttributeError: 'result' object has no attribute 'group_key'
```

#### How to reproduce the bug

1. Create a Regular Row Level Security Filter for your role and a table in superset. 
2. Open the table in 'Explore" mode
3. Run a simple table row count (default view)

### Environment
- superset version: 0.38.0
- python version: 3.7.9
- node.js version: N/A

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by oscarostlundgs** [comment]
This issue is due to a customized security manager that we are using and hence not related to Superset 0.38.
