### ISSUE TITLE
iframe viz broken in 0.28.1

### ISSUE THREAD

**Issue by MikeRoetgers** [apache/incubator-superset#6177]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.28.1

### Expected results
When adding an iframe visualization I would expect to see the configured website in the iframe. This worked fine with 0.27.0 and unfortunately stopped working after upgrading to 0.28.1

### Actual results
Python stacktrace:

```
2018-10-24 17:29:35,444:DEBUG:root:[stats_logger] (incr) explore_json
2018-10-24 17:29:35,626:INFO:root:Cache key: None
2018-10-24 17:29:35,626:ERROR:root:'NoneType' object has no attribute 'to_dict'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/superset/views/core.py", line 1149, in generate_json
    payload = viz_obj.get_payload()
  File "/usr/local/lib/python3.6/dist-packages/superset/viz.py", line 371, in get_payload
    payload['data'] = self.get_data(df)
  File "/usr/local/lib/python3.6/dist-packages/superset/viz.py", line 485, in get_data
    return self.get_df().to_dict(orient='records')
AttributeError: 'NoneType' object has no attribute 'to_dict'
2018-10-24 17:29:35,694:DEBUG:root:[stats_logger] (incr) log
```

I'm seeing it calling `/superset/explore_json` which ends in a 500 with the body:

```
{"error": "'NoneType' object has no attribute 'to_dict'"}
```

I'm gonna take a look myself tomorrow. Just wanted to put it here in case someone else is running into it. 

### Steps to reproduce

* Add a new iframe visualization
* Configure the URL under Options
* Press `Run Query` or add it to a dashboard
